#!/bin/bash

#CARREGANDO AS FUNÇÕES E VARIÁVEIS NECESSÁRIAS
BASE_DIR="$HOME/.terminalThemes"
FUNCTIONS_FILE="$BASE_DIR/terminal_theme_functions"
source "$FUNCTIONS_FILE"


# VERIFICA SE O $LAST_THEME EXISTE
touch "$LAST_THEME"


FZF_BASE="--height=40% --reverse --border"

#  ============ MENU OPTIONS ====================
opt_0_0="✞ Alterar prompt"
opt_0_1="✞ Alterar background img"
opt_0_2="✞ Reset all"
opt_0_3="✞ Combo!!!"
opt_0_4="✞ adicionar / remover bk_img"
    opt_0_4_0="✞ adicionar bk_img"
    opt_0_4_1="✞ remover o bk_img"
    opt_0_4_2="✞ puxar o bk_img (Do lixo)"

# ============= MENU HIDDEN / STRANGER OPTIONS =============
EXIT_OPTION="✞ SAIR"
#  ============ MENU OPTIONS ====================
while true; do
OPTION=$(printf "$opt_0_0
$opt_0_1
$opt_0_2
$opt_0_3
$opt_0_4
$EXIT_OPTION" | fzf $FZF_BASE --prompt="✞ OPTION ➤ ")


case $OPTION in

    # 1
    "$opt_0_0")
        ps1=$(ls "$PS1_DIR" | fzf \
        --preview " [ -f "$PS1_DIR/{}" ] && cat "$PS1_DIR/{}" || [ -d "$PS1_DIR/{}" ] && ls "$PS1_DIR/{}" " \
        $FZF_BASE \
        --prompt="✞ PS1 OPTION ⤸ "
        )
        apply_ps1 $PS1_DIR/$ps1
        echo -e "\033[0;32mPS1 SELECIONADO: $ps1\033[0m"
    ;;
    # 2
    "$opt_0_1")
        bk_img=$(ls $BG_IMG_DIR | fzf $FZF_BASE --prompt="✞ BACKGROUND OPTION ⤸")
        set_kitty_image "$BG_IMG_DIR/$bk_img"
        echo -e "\033[0;32mBACKGROUND SELECIONADO: $bk_img\033[0m"
    ;;
    # 3
    "$opt_0_2")
        reset_full
        echo -e '\033[0;32mPS1 & Backround resetados\033[0m'
    ;;
    # 4
    "$opt_0_3")
        ps1=$(ls "$PS1_DIR" | fzf \
          --preview " [ -f "$PS1_DIR/{}" ] && cat "$PS1_DIR/{}" || [ -d "$PS1_DIR/{}" ] && ls "$PS1_DIR/{}" " \
          $FZF_BASE \
          --prompt="✞ PS1 OPTION (MENU COMBO) ⤸ "
        )
        apply_ps1 $PS1_DIR/$ps1    
        echo -e "\033[0;32mPS1 SELECIONADO: $ps1\033[0m"

        bk_img=$(ls $BG_IMG_DIR | fzf $FZF_BASE --prompt="✞ BACKGROUND OPTION (MENU COMBO) ⤸")
        set_kitty_image "$BG_IMG_DIR/$bk_img"
        echo -e "\033[0;32mBACKGROUND SELECIONADO: $bk_img\033[0m"
        
    ;;
    # 5
    "$opt_0_4")
        bk_or_prompt=$( printf "$opt_0_4_0\n$opt_0_4_1\n$opt_0_4_2" | fzf --reverse )

        case "$bk_or_prompt" in 

            # 5_0 - add bk_img
            "$opt_0_4_0")
                bk_ch=$(fzf --reverse)
                include_bk_img "$bk_ch"

            ;;
            # 5_1 - remove bk_img
            "$opt_0_4_1")
                bk_ch=$( ls $BG_IMG_DIR | fzf --reverse )
                remove_bk_img "$bk_ch"
            ;;
            # 5_1 - puxa o bk_img do lixo
            "$opt_0_4_2")
               restore_img_from_trash "✞ GARBAGE COLLECTION ⤸" - 11 # o sinal e a quantidade de carácteres retirados do final do arquivo final
            ;;
            # Exception for $bk_or_prompt
            *)
                printf '\e[31mOption not found\e[0m\n'
            ;;

        esac
    ;;
    #   Exception for $OPTION
    "$EXIT_OPTION")
        printf '\e[31mSaindo do programa\e[0m\n'
        break
    ;;
    *)
        printf '\e[31mOption not found\e[0m\n'
    ;;
    esac
done