#!/bin/bash
BASE_DIR="$HOME/.terminalThemes"
LAST_THEME="$BASE_DIR/.my_last_theme"


PS1_DIR="$BASE_DIR/PS1s"
BG_DIR="$BASE_DIR/backgrounds"
BG_IMG_DIR="$BASE_DIR/backgrounds/imgs"


KEY_LT_BACKGROUND_IMG="THEME_BACKGROUND_IMG"
KEY_LT_PS1="THEME_PS1"

LIXO="$BASE_DIR/.temp"
LIXO_BK="$LIXO/bk_remove"


mkdir -p "$LIXO"
mkdir -p "$LIXO_BK"

# VERIFICA SE O $LAST_THEME EXISTE

[ ! -e "$LAST_THEME" ] && touch "$LAST_THEME"

#=========== - = - = - = - = ALTERAR COLUNA DO ".my_last_theme" = - = - = - = - ==========

alter_colun() {
    local key="$1"
    local new_value="$2"
    local file="$LAST_THEME"

    if grep -q "^${key}=" "$file"; then
        sed -i "s|^${key}=.*|${key}=${new_value}|" "$file"
    else
        echo "${key}=${new_value}\n" >> "$file"
    fi
}
#=========== - = - = - = - = end

#=========== - = - = - = - = ALTERAR O BACKGROUND-IMAGE

set_kitty_image() {
    if [ "$TERM" = "xterm-kitty" ]; then
        local IMAGE_PATH="$1"
        if [ "$IMAGE_PATH" = "none" ]; then
          kitty @ set-background-image none 2>/dev/null
          alter_colun "$KEY_LT_BACKGROUND_IMG" "none"
  	else
          kitten @ set-background-image "$IMAGE_PATH"
          alter_colun "$KEY_LT_BACKGROUND_IMG" "$IMAGE_PATH"
        fi
    else
      echo "Your terminal is $TERM, the function set_kitty_background only works in terminals kitty"
    fi
}
#=========== - = - = - = - = END

#=========== - = - = - = - = RESETAR O TEMA
reset_full() {
  # reset PS1 padrão
  PS1='\[\e[01;32m\]\u@\h\[\e[00m\]:\[\e[01;34m\]\w\[\e[00m\]\$ '
  # reset cores
  printf '\033]12;#ffffff\007'   # cursor branco
  printf '\033]11;#000000\007'   # fundo preto
  printf '\033]10;#ffffff\007'   # texto branco

  # remove imagem se o terminal for o kitty
  if [ "$TERM" = 'xterm-kitty' ]; then
  	kitty @ set-background-image none 2>/dev/null
    alter_colun "$KEY_LT_BACKGROUND_IMG" "none" 
  else
	echo cara nem tem background KASKJSAKJSAKJASJKASKJASKJASJKSAJKAS
  	return 0
  fi
  # seta o PS1 pro valor deafult
  alter_colun "$KEY_LT_PS1" "deafult"
}

#=========== - = - = - = - = END

#=========== - = - = - = - = PUXANDO O PS1 DO CAMINHO E ALTERANDO

apply_ps1(){
  local PS1_PATH="$1"
  if [ $PS1_PATH = "$PS1_PATH/deafult" ]; then
    alter_colun "$KEY_LT_PS1" "$PS1_PATH"
    PS1='\[\e[01;32m\]\u@\h\[\e[00m\]:\[\e[01;34m\]\w\[\e[00m\]\$ '
  else
    source "$PS1_PATH" && alter_colun "$KEY_LT_PS1" "$PS1_PATH" 
  fi
}

include_bk_img(){
  local bk_ch=$1
  local mime=$(file --mime-type -b "$bk_ch")
  if [[ "$mime" == image/* ]]; then
      cp "$bk_ch" "$BG_IMG_DIR"
      printf '\e[32mImage added\e[0m\n'
  else
      printf '\e[31mnot image\e[0m\n'
  fi
}

include_prompt(){
  local prompt_ch=$1
  local mime=$(file --mime-type -b "$bk_ch")
  if [[ "$mime" == text/* ]]; then
      cp "$prompt_ch" "$PS1_DIR"
      printf '\e[32mPS1 added\e[0m\n'
  else
      printf '\e[31mnot text\e[0m\n'
  fi
}

remove_bk_img(){
  local bk_ch=$1
  local mime=$(file --mime-type -b "$BG_IMG_DIR/$bk_ch")
  echo "$BG_IMG_DIR/$bk_ch"
  if [[ "$mime" == image/* ]]; then
      mv "$BG_IMG_DIR/$bk_ch" "$LIXO_BK/$bk_ch-$( date +%s )"
      printf '\e[31mImage deleted\e[0m\n'
  else
      printf '\e[32mnot image\e[0m\n'
  fi
}

restore_img_from_trash(){
  local prompt=$1 # O que vai ser 
  local signal=$2 # Se vai tirar de frente ou de trás 
  local quant=$3 # quantidade de caracteres retirados de frente e de trás
  local bk_ch=$(ls "$LIXO_BK" | fzf $FZF_BASE --prompt="$prompt")
  # echo "bk_ch: $bk_ch"
  # echo "prompt: $prompt"
  # echo "signal: $signal"
  # echo "quant: $quant"
  local mime=$(file --mime-type -b "$LIXO_BK/$bk_ch")
  
  if [[ "$mime" == image/* ]]; then
      mv "$LIXO_BK/$bk_ch" "$BG_IMG_DIR/$(basename ${bk_ch::$signal$quant})" && printf '\e[32mImage recovered\e[0m\n'
  else
      printf '\e[31mnot image\e[0m\n'
  fi
}

#  FUNÇÃO QUE VAI SER TRATADA PARA PEGAR SOMENTE O VALOR DE PS1 E INSERIR
#apply_ps1(){
#  local PS1_PATH="$1"
#  local content=$( cat "$PS1_PATH" )
#  if [ $PS1_PATH = "deafult" ]; then
#    alter_colun "$KEY_LT_PS1" "$PS1_PATH"
#    PS1='\[\e[01;32m\]\u@\h\[\e[00m\]:\[\e[01;34m\]\w\[\e[00m\]\$ '
#  else
#    PS1="$content" && alter_colun "$KEY_LT_PS1" "$PS1_PATH"
#  fi
#}
